### ISSUE TITLE
Feature : Option to Follow Redirections

### ISSUE THREAD

**Issue by arbazkiraak** [Static-Flow/DirectoryImporter#2]
Hello @Static-Flow ,

* Loading lot of URLs and making HTTP Requests often makes `30X` redirection requests, I Request a feature which adds a checkbox to ask the user to follow redirection while making httpRequest()

Workflow on check :

```
1.  makeHttpRequest(httpService,None)
2.  check if the response is indicating any redirections.
3.  perform redirection my making `step 1`
4.  add above `redirected` request of step 3 and `response` to the siteMap.
```

**Comment by Static-Flow** [comment]
I just added this and totally forgot to update this feature request! It now supports 3 deep redirects.
