### ISSUE TITLE
[Feature] Support Threading

### ISSUE THREAD

**Issue by arbazkiraak** [Static-Flow/DirectoryImporter#3]
Hello @Static-Flow ,

> While making http request across a list of URLs, it would be quick to have multithreading

**Comment by Static-Flow** [comment]
It already is:

                        Runnable task2 =
                                () -> this.callbacks.addToSiteMap(
                                        this.callbacks.makeHttpRequest(
                                                requestResponse.getHttpService(),
                                                requestResponse.getRequest()));
                        new Thread(task2).start();
